// Code generated by protoc-gen-go.
// source: protoeasy.proto
// DO NOT EDIT!

package protoeasy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "go.pedge.io/pb/go/google/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GoPluginType int32

const (
	GoPluginType_GO_PLUGIN_TYPE_NONE   GoPluginType = 0
	GoPluginType_GO_PLUGIN_TYPE_GO     GoPluginType = 1
	GoPluginType_GO_PLUGIN_TYPE_GOFAST GoPluginType = 2
)

var GoPluginType_name = map[int32]string{
	0: "GO_PLUGIN_TYPE_NONE",
	1: "GO_PLUGIN_TYPE_GO",
	2: "GO_PLUGIN_TYPE_GOFAST",
}
var GoPluginType_value = map[string]int32{
	"GO_PLUGIN_TYPE_NONE":   0,
	"GO_PLUGIN_TYPE_GO":     1,
	"GO_PLUGIN_TYPE_GOFAST": 2,
}

func (x GoPluginType) String() string {
	return proto.EnumName(GoPluginType_name, int32(x))
}
func (GoPluginType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GogoPluginType int32

const (
	GogoPluginType_GOGO_PLUGIN_TYPE_NONE       GogoPluginType = 0
	GogoPluginType_GOGO_PLUGIN_TYPE_GOGO       GogoPluginType = 1
	GogoPluginType_GOGO_PLUGIN_TYPE_GOGOFAST   GogoPluginType = 2
	GogoPluginType_GOGO_PLUGIN_TYPE_GOGOFASTER GogoPluginType = 3
	GogoPluginType_GOGO_PLUGIN_TYPE_GOGOSLICK  GogoPluginType = 4
)

var GogoPluginType_name = map[int32]string{
	0: "GOGO_PLUGIN_TYPE_NONE",
	1: "GOGO_PLUGIN_TYPE_GOGO",
	2: "GOGO_PLUGIN_TYPE_GOGOFAST",
	3: "GOGO_PLUGIN_TYPE_GOGOFASTER",
	4: "GOGO_PLUGIN_TYPE_GOGOSLICK",
}
var GogoPluginType_value = map[string]int32{
	"GOGO_PLUGIN_TYPE_NONE":       0,
	"GOGO_PLUGIN_TYPE_GOGO":       1,
	"GOGO_PLUGIN_TYPE_GOGOFAST":   2,
	"GOGO_PLUGIN_TYPE_GOGOFASTER": 3,
	"GOGO_PLUGIN_TYPE_GOGOSLICK":  4,
}

func (x GogoPluginType) String() string {
	return proto.EnumName(GogoPluginType_name, int32(x))
}
func (GogoPluginType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CompileOptions struct {
	Grpc                        bool              `protobuf:"varint,1,opt,name=grpc" json:"grpc,omitempty"`
	GrpcGateway                 bool              `protobuf:"varint,2,opt,name=grpc_gateway,json=grpcGateway" json:"grpc_gateway,omitempty"`
	NoDefaultIncludes           bool              `protobuf:"varint,3,opt,name=no_default_includes,json=noDefaultIncludes" json:"no_default_includes,omitempty"`
	ExcludePattern              []string          `protobuf:"bytes,4,rep,name=exclude_pattern,json=excludePattern" json:"exclude_pattern,omitempty"`
	RelContext                  string            `protobuf:"bytes,5,opt,name=rel_context,json=relContext" json:"rel_context,omitempty"`
	ExtraPluginFlag             []string          `protobuf:"bytes,6,rep,name=extra_plugin_flag,json=extraPluginFlag" json:"extra_plugin_flag,omitempty"`
	Cpp                         bool              `protobuf:"varint,20,opt,name=cpp" json:"cpp,omitempty"`
	CppRelOut                   string            `protobuf:"bytes,21,opt,name=cpp_rel_out,json=cppRelOut" json:"cpp_rel_out,omitempty"`
	Csharp                      bool              `protobuf:"varint,30,opt,name=csharp" json:"csharp,omitempty"`
	CsharpRelOut                string            `protobuf:"bytes,31,opt,name=csharp_rel_out,json=csharpRelOut" json:"csharp_rel_out,omitempty"`
	Go                          bool              `protobuf:"varint,40,opt,name=go" json:"go,omitempty"`
	GoPluginType                GoPluginType      `protobuf:"varint,41,opt,name=go_plugin_type,json=goPluginType,enum=protoeasy.GoPluginType" json:"go_plugin_type,omitempty"`
	GoRelOut                    string            `protobuf:"bytes,42,opt,name=go_rel_out,json=goRelOut" json:"go_rel_out,omitempty"`
	GoImportPath                string            `protobuf:"bytes,43,opt,name=go_import_path,json=goImportPath" json:"go_import_path,omitempty"`
	GoNoDefaultModifiers        bool              `protobuf:"varint,44,opt,name=go_no_default_modifiers,json=goNoDefaultModifiers" json:"go_no_default_modifiers,omitempty"`
	GoModifiers                 map[string]string `protobuf:"bytes,45,rep,name=go_modifiers,json=goModifiers" json:"go_modifiers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Gogo                        bool              `protobuf:"varint,50,opt,name=gogo" json:"gogo,omitempty"`
	GogoPluginType              GogoPluginType    `protobuf:"varint,51,opt,name=gogo_plugin_type,json=gogoPluginType,enum=protoeasy.GogoPluginType" json:"gogo_plugin_type,omitempty"`
	GogoRelOut                  string            `protobuf:"bytes,52,opt,name=gogo_rel_out,json=gogoRelOut" json:"gogo_rel_out,omitempty"`
	GogoImportPath              string            `protobuf:"bytes,53,opt,name=gogo_import_path,json=gogoImportPath" json:"gogo_import_path,omitempty"`
	GogoNoDefaultModifiers      bool              `protobuf:"varint,54,opt,name=gogo_no_default_modifiers,json=gogoNoDefaultModifiers" json:"gogo_no_default_modifiers,omitempty"`
	GogoModifiers               map[string]string `protobuf:"bytes,55,rep,name=gogo_modifiers,json=gogoModifiers" json:"gogo_modifiers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Objc                        bool              `protobuf:"varint,60,opt,name=objc" json:"objc,omitempty"`
	ObjcRelOut                  string            `protobuf:"bytes,61,opt,name=objc_rel_out,json=objcRelOut" json:"objc_rel_out,omitempty"`
	Python                      bool              `protobuf:"varint,70,opt,name=python" json:"python,omitempty"`
	PythonRelOut                string            `protobuf:"bytes,71,opt,name=python_rel_out,json=pythonRelOut" json:"python_rel_out,omitempty"`
	Ruby                        bool              `protobuf:"varint,80,opt,name=ruby" json:"ruby,omitempty"`
	RubyRelOut                  string            `protobuf:"bytes,81,opt,name=ruby_rel_out,json=rubyRelOut" json:"ruby_rel_out,omitempty"`
	DescriptorSet               bool              `protobuf:"varint,90,opt,name=descriptor_set,json=descriptorSet" json:"descriptor_set,omitempty"`
	DescriptorSetRelOut         string            `protobuf:"bytes,91,opt,name=descriptor_set_rel_out,json=descriptorSetRelOut" json:"descriptor_set_rel_out,omitempty"`
	DescriptorSetFileName       string            `protobuf:"bytes,92,opt,name=descriptor_set_file_name,json=descriptorSetFileName" json:"descriptor_set_file_name,omitempty"`
	DescriptorSetIncludeImports bool              `protobuf:"varint,93,opt,name=descriptor_set_include_imports,json=descriptorSetIncludeImports" json:"descriptor_set_include_imports,omitempty"`
	GoMicro                     bool              `protobuf:"varint,100,opt,name=go_micro,json=goMicro" json:"go_micro,omitempty"`
}

func (m *CompileOptions) Reset()                    { *m = CompileOptions{} }
func (m *CompileOptions) String() string            { return proto.CompactTextString(m) }
func (*CompileOptions) ProtoMessage()               {}
func (*CompileOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CompileOptions) GetGrpc() bool {
	if m != nil {
		return m.Grpc
	}
	return false
}

func (m *CompileOptions) GetGrpcGateway() bool {
	if m != nil {
		return m.GrpcGateway
	}
	return false
}

func (m *CompileOptions) GetNoDefaultIncludes() bool {
	if m != nil {
		return m.NoDefaultIncludes
	}
	return false
}

func (m *CompileOptions) GetExcludePattern() []string {
	if m != nil {
		return m.ExcludePattern
	}
	return nil
}

func (m *CompileOptions) GetRelContext() string {
	if m != nil {
		return m.RelContext
	}
	return ""
}

func (m *CompileOptions) GetExtraPluginFlag() []string {
	if m != nil {
		return m.ExtraPluginFlag
	}
	return nil
}

func (m *CompileOptions) GetCpp() bool {
	if m != nil {
		return m.Cpp
	}
	return false
}

func (m *CompileOptions) GetCppRelOut() string {
	if m != nil {
		return m.CppRelOut
	}
	return ""
}

func (m *CompileOptions) GetCsharp() bool {
	if m != nil {
		return m.Csharp
	}
	return false
}

func (m *CompileOptions) GetCsharpRelOut() string {
	if m != nil {
		return m.CsharpRelOut
	}
	return ""
}

func (m *CompileOptions) GetGo() bool {
	if m != nil {
		return m.Go
	}
	return false
}

func (m *CompileOptions) GetGoPluginType() GoPluginType {
	if m != nil {
		return m.GoPluginType
	}
	return GoPluginType_GO_PLUGIN_TYPE_NONE
}

func (m *CompileOptions) GetGoRelOut() string {
	if m != nil {
		return m.GoRelOut
	}
	return ""
}

func (m *CompileOptions) GetGoImportPath() string {
	if m != nil {
		return m.GoImportPath
	}
	return ""
}

func (m *CompileOptions) GetGoNoDefaultModifiers() bool {
	if m != nil {
		return m.GoNoDefaultModifiers
	}
	return false
}

func (m *CompileOptions) GetGoModifiers() map[string]string {
	if m != nil {
		return m.GoModifiers
	}
	return nil
}

func (m *CompileOptions) GetGogo() bool {
	if m != nil {
		return m.Gogo
	}
	return false
}

func (m *CompileOptions) GetGogoPluginType() GogoPluginType {
	if m != nil {
		return m.GogoPluginType
	}
	return GogoPluginType_GOGO_PLUGIN_TYPE_NONE
}

func (m *CompileOptions) GetGogoRelOut() string {
	if m != nil {
		return m.GogoRelOut
	}
	return ""
}

func (m *CompileOptions) GetGogoImportPath() string {
	if m != nil {
		return m.GogoImportPath
	}
	return ""
}

func (m *CompileOptions) GetGogoNoDefaultModifiers() bool {
	if m != nil {
		return m.GogoNoDefaultModifiers
	}
	return false
}

func (m *CompileOptions) GetGogoModifiers() map[string]string {
	if m != nil {
		return m.GogoModifiers
	}
	return nil
}

func (m *CompileOptions) GetObjc() bool {
	if m != nil {
		return m.Objc
	}
	return false
}

func (m *CompileOptions) GetObjcRelOut() string {
	if m != nil {
		return m.ObjcRelOut
	}
	return ""
}

func (m *CompileOptions) GetPython() bool {
	if m != nil {
		return m.Python
	}
	return false
}

func (m *CompileOptions) GetPythonRelOut() string {
	if m != nil {
		return m.PythonRelOut
	}
	return ""
}

func (m *CompileOptions) GetRuby() bool {
	if m != nil {
		return m.Ruby
	}
	return false
}

func (m *CompileOptions) GetRubyRelOut() string {
	if m != nil {
		return m.RubyRelOut
	}
	return ""
}

func (m *CompileOptions) GetDescriptorSet() bool {
	if m != nil {
		return m.DescriptorSet
	}
	return false
}

func (m *CompileOptions) GetDescriptorSetRelOut() string {
	if m != nil {
		return m.DescriptorSetRelOut
	}
	return ""
}

func (m *CompileOptions) GetDescriptorSetFileName() string {
	if m != nil {
		return m.DescriptorSetFileName
	}
	return ""
}

func (m *CompileOptions) GetDescriptorSetIncludeImports() bool {
	if m != nil {
		return m.DescriptorSetIncludeImports
	}
	return false
}

func (m *CompileOptions) GetGoMicro() bool {
	if m != nil {
		return m.GoMicro
	}
	return false
}

type Command struct {
	Arg []string `protobuf:"bytes,1,rep,name=arg" json:"arg,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Command) GetArg() []string {
	if m != nil {
		return m.Arg
	}
	return nil
}

type CompileInfo struct {
	Command         []*Command                `protobuf:"bytes,1,rep,name=command" json:"command,omitempty"`
	InputSizeBytes  uint64                    `protobuf:"varint,2,opt,name=input_size_bytes,json=inputSizeBytes" json:"input_size_bytes,omitempty"`
	OutputSizeBytes uint64                    `protobuf:"varint,3,opt,name=output_size_bytes,json=outputSizeBytes" json:"output_size_bytes,omitempty"`
	Duration        *google_protobuf.Duration `protobuf:"bytes,4,opt,name=duration" json:"duration,omitempty"`
}

func (m *CompileInfo) Reset()                    { *m = CompileInfo{} }
func (m *CompileInfo) String() string            { return proto.CompactTextString(m) }
func (*CompileInfo) ProtoMessage()               {}
func (*CompileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CompileInfo) GetCommand() []*Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *CompileInfo) GetInputSizeBytes() uint64 {
	if m != nil {
		return m.InputSizeBytes
	}
	return 0
}

func (m *CompileInfo) GetOutputSizeBytes() uint64 {
	if m != nil {
		return m.OutputSizeBytes
	}
	return 0
}

func (m *CompileInfo) GetDuration() *google_protobuf.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type CompileRequest struct {
	Tar            []byte          `protobuf:"bytes,1,opt,name=tar,proto3" json:"tar,omitempty"`
	CompileOptions *CompileOptions `protobuf:"bytes,2,opt,name=compile_options,json=compileOptions" json:"compile_options,omitempty"`
}

func (m *CompileRequest) Reset()                    { *m = CompileRequest{} }
func (m *CompileRequest) String() string            { return proto.CompactTextString(m) }
func (*CompileRequest) ProtoMessage()               {}
func (*CompileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CompileRequest) GetTar() []byte {
	if m != nil {
		return m.Tar
	}
	return nil
}

func (m *CompileRequest) GetCompileOptions() *CompileOptions {
	if m != nil {
		return m.CompileOptions
	}
	return nil
}

type CompileResponse struct {
	Tar         []byte       `protobuf:"bytes,1,opt,name=tar,proto3" json:"tar,omitempty"`
	CompileInfo *CompileInfo `protobuf:"bytes,2,opt,name=compile_info,json=compileInfo" json:"compile_info,omitempty"`
}

func (m *CompileResponse) Reset()                    { *m = CompileResponse{} }
func (m *CompileResponse) String() string            { return proto.CompactTextString(m) }
func (*CompileResponse) ProtoMessage()               {}
func (*CompileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CompileResponse) GetTar() []byte {
	if m != nil {
		return m.Tar
	}
	return nil
}

func (m *CompileResponse) GetCompileInfo() *CompileInfo {
	if m != nil {
		return m.CompileInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*CompileOptions)(nil), "protoeasy.CompileOptions")
	proto.RegisterType((*Command)(nil), "protoeasy.Command")
	proto.RegisterType((*CompileInfo)(nil), "protoeasy.CompileInfo")
	proto.RegisterType((*CompileRequest)(nil), "protoeasy.CompileRequest")
	proto.RegisterType((*CompileResponse)(nil), "protoeasy.CompileResponse")
	proto.RegisterEnum("protoeasy.GoPluginType", GoPluginType_name, GoPluginType_value)
	proto.RegisterEnum("protoeasy.GogoPluginType", GogoPluginType_name, GogoPluginType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	out := new(CompileResponse)
	err := grpc.Invoke(ctx, "/protoeasy.API/Compile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	Compile(context.Context, *CompileRequest) (*CompileResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoeasy.API/Compile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Compile(ctx, req.(*CompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoeasy.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _API_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoeasy.proto",
}

func init() { proto.RegisterFile("protoeasy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x55, 0xed, 0x72, 0xdb, 0x44,
	0x17, 0xae, 0x62, 0x37, 0x89, 0x8f, 0x5c, 0xd9, 0xd9, 0x7c, 0xad, 0x9d, 0xf7, 0x4d, 0x8c, 0xa7,
	0x0c, 0x26, 0x04, 0x77, 0xc6, 0x21, 0x94, 0x32, 0x94, 0xa1, 0x71, 0x13, 0x8f, 0x87, 0x26, 0x31,
	0x72, 0xf8, 0x51, 0xbe, 0x34, 0xb2, 0xbc, 0xde, 0x08, 0x64, 0xad, 0x90, 0x56, 0x10, 0xf7, 0x82,
	0xb8, 0x16, 0x7e, 0x70, 0x51, 0xcc, 0xee, 0xca, 0xb2, 0xe4, 0x18, 0x66, 0xf8, 0xa5, 0xb3, 0xcf,
	0x79, 0xce, 0x87, 0x9e, 0x3d, 0x3a, 0x82, 0x4a, 0x10, 0x32, 0xce, 0x88, 0x1d, 0xcd, 0xda, 0xd2,
	0x42, 0xa5, 0x14, 0xa8, 0x1f, 0x52, 0xc6, 0xa8, 0x47, 0x9e, 0x49, 0x64, 0x14, 0x4f, 0x9e, 0x8d,
	0xe3, 0xd0, 0xe6, 0x2e, 0xf3, 0x15, 0xb5, 0xf9, 0x97, 0x0e, 0x46, 0x97, 0x4d, 0x03, 0xd7, 0x23,
	0x37, 0x81, 0xc0, 0x23, 0x84, 0xa0, 0x48, 0xc3, 0xc0, 0xc1, 0x5a, 0x43, 0x6b, 0x6d, 0x9a, 0xd2,
	0x46, 0xef, 0x41, 0x59, 0x3c, 0x2d, 0x6a, 0x73, 0xf2, 0xbb, 0x3d, 0xc3, 0x6b, 0xd2, 0xa7, 0x0b,
	0xac, 0xa7, 0x20, 0xd4, 0x86, 0x6d, 0x9f, 0x59, 0x63, 0x32, 0xb1, 0x63, 0x8f, 0x5b, 0xae, 0xef,
	0x78, 0xf1, 0x98, 0x44, 0xb8, 0x20, 0x99, 0x5b, 0x3e, 0x7b, 0xad, 0x3c, 0xfd, 0xc4, 0x81, 0x3e,
	0x80, 0x0a, 0xb9, 0x97, 0xb6, 0x15, 0xd8, 0x9c, 0x93, 0xd0, 0xc7, 0xc5, 0x46, 0xa1, 0x55, 0x32,
	0x8d, 0x04, 0x1e, 0x28, 0x14, 0x1d, 0x81, 0x1e, 0x12, 0xcf, 0x72, 0x98, 0xcf, 0xc9, 0x3d, 0xc7,
	0x8f, 0x1b, 0x5a, 0xab, 0x64, 0x42, 0x48, 0xbc, 0xae, 0x42, 0xd0, 0x31, 0x6c, 0x91, 0x7b, 0x1e,
	0xda, 0x56, 0xe0, 0xc5, 0xd4, 0xf5, 0xad, 0x89, 0x67, 0x53, 0xbc, 0x2e, 0x73, 0x55, 0xa4, 0x63,
	0x20, 0xf1, 0x4b, 0xcf, 0xa6, 0xa8, 0x0a, 0x05, 0x27, 0x08, 0xf0, 0x8e, 0xec, 0x4a, 0x98, 0xe8,
	0x10, 0x74, 0x27, 0x08, 0x2c, 0x51, 0x82, 0xc5, 0x1c, 0xef, 0xca, 0xf4, 0x25, 0x27, 0x08, 0x4c,
	0xe2, 0xdd, 0xc4, 0x1c, 0xed, 0xc1, 0xba, 0x13, 0xdd, 0xd9, 0x61, 0x80, 0x0f, 0x65, 0x50, 0x72,
	0x42, 0x4f, 0xc1, 0x50, 0x56, 0x1a, 0x7a, 0x24, 0x43, 0xcb, 0x0a, 0x4d, 0xa2, 0x0d, 0x58, 0xa3,
	0x0c, 0xb7, 0x64, 0xe4, 0x1a, 0x65, 0xe8, 0x25, 0x18, 0x94, 0xcd, 0x1b, 0xe5, 0xb3, 0x80, 0xe0,
	0x0f, 0x1b, 0x5a, 0xcb, 0xe8, 0xec, 0xb7, 0x17, 0x97, 0xd8, 0x63, 0xaa, 0xe1, 0xdb, 0x59, 0x40,
	0xcc, 0x32, 0xcd, 0x9c, 0xd0, 0xff, 0x00, 0x28, 0x4b, 0x0b, 0x1e, 0xcb, 0x82, 0x9b, 0x94, 0x25,
	0xc5, 0x9e, 0xca, 0xe4, 0xee, 0x34, 0x60, 0x21, 0x17, 0xa2, 0xde, 0xe1, 0x8f, 0x54, 0x4b, 0x94,
	0xf5, 0x25, 0x38, 0xb0, 0xf9, 0x1d, 0x3a, 0x83, 0x7d, 0xca, 0xac, 0xcc, 0x5d, 0x4d, 0xd9, 0xd8,
	0x9d, 0xb8, 0x24, 0x8c, 0xf0, 0x89, 0xec, 0x73, 0x87, 0xb2, 0xeb, 0xf9, 0x75, 0x5d, 0xcd, 0x7d,
	0xe8, 0x0a, 0xca, 0x94, 0x65, 0xb8, 0x1f, 0x37, 0x0a, 0x2d, 0xbd, 0x73, 0x9c, 0xe9, 0x3b, 0x3f,
	0x47, 0xed, 0x1e, 0x4b, 0x83, 0x2f, 0x7c, 0x1e, 0xce, 0x4c, 0x9d, 0x2e, 0x10, 0x39, 0x65, 0x8c,
	0x32, 0xdc, 0x49, 0xa6, 0x8c, 0x51, 0x86, 0xba, 0x50, 0x15, 0xcf, 0x9c, 0x3c, 0xa7, 0x52, 0x9e,
	0x5a, 0x4e, 0x9e, 0xac, 0x24, 0xa6, 0x41, 0x73, 0x67, 0xd4, 0x10, 0x7d, 0x66, 0x44, 0xfa, 0x44,
	0xcd, 0x8b, 0xc0, 0x12, 0x99, 0x5a, 0x49, 0x99, 0xac, 0x50, 0x67, 0x92, 0x25, 0x73, 0x65, 0xa4,
	0x7a, 0x01, 0x35, 0xc9, 0x5c, 0x29, 0xd6, 0xa7, 0xb2, 0xf3, 0x3d, 0x41, 0x58, 0x21, 0xd7, 0x10,
	0x64, 0xb2, 0x0c, 0xff, 0xb9, 0x14, 0xec, 0xe4, 0xdf, 0x04, 0xa3, 0xcb, 0x92, 0x3d, 0xa1, 0x6c,
	0x49, 0x34, 0x36, 0xfa, 0xd9, 0xc1, 0x5f, 0x28, 0xd1, 0x84, 0x2d, 0xde, 0x57, 0x3c, 0xd3, 0xf7,
	0x7d, 0xa9, 0xde, 0x57, 0x60, 0x8b, 0x09, 0x0e, 0x66, 0xfc, 0x8e, 0xf9, 0xf8, 0x52, 0x4d, 0xb0,
	0x3a, 0x89, 0x71, 0x51, 0x56, 0x1a, 0xdb, 0x53, 0xe3, 0xa2, 0xd0, 0x24, 0x1a, 0x41, 0x31, 0x8c,
	0x47, 0x33, 0x3c, 0x50, 0x35, 0x85, 0x2d, 0x6a, 0x8a, 0x67, 0x1a, 0xf7, 0x4d, 0xf2, 0x4d, 0xc6,
	0xa3, 0x59, 0x12, 0xf5, 0x3e, 0x18, 0x63, 0x12, 0x39, 0xa1, 0x1b, 0x70, 0x16, 0x5a, 0x11, 0xe1,
	0xf8, 0x3b, 0x19, 0xff, 0x64, 0x81, 0x0e, 0x09, 0x47, 0xa7, 0xb0, 0x97, 0xa7, 0xa5, 0x29, 0xbf,
	0x97, 0x29, 0xb7, 0x73, 0xf4, 0x24, 0xf7, 0x73, 0xc0, 0x4b, 0x41, 0x13, 0xd7, 0x23, 0x96, 0x6f,
	0x4f, 0x09, 0xfe, 0x41, 0x86, 0xed, 0xe6, 0xc2, 0x2e, 0x5d, 0x8f, 0x5c, 0xdb, 0x53, 0x82, 0xba,
	0x70, 0xb8, 0x14, 0x98, 0xac, 0xa9, 0x64, 0x14, 0x22, 0xfc, 0xa3, 0x6c, 0xf2, 0x20, 0x17, 0x9e,
	0x6c, 0x2c, 0x35, 0x16, 0x11, 0xaa, 0xc1, 0xa6, 0xb8, 0x56, 0xd7, 0x09, 0x19, 0x1e, 0x4b, 0xfa,
	0x06, 0x65, 0x57, 0xe2, 0x58, 0xff, 0x12, 0xaa, 0xcb, 0x43, 0x2f, 0x16, 0xce, 0x2f, 0x64, 0x26,
	0x97, 0x69, 0xc9, 0x14, 0x26, 0xda, 0x81, 0xc7, 0xbf, 0xd9, 0x5e, 0x4c, 0xe4, 0x12, 0x2d, 0x99,
	0xea, 0xf0, 0xf9, 0xda, 0x67, 0x5a, 0xfd, 0x2b, 0x40, 0x0f, 0x67, 0xe0, 0xbf, 0x64, 0x68, 0x1e,
	0xc0, 0x46, 0x97, 0x4d, 0xa7, 0xb6, 0x3f, 0x16, 0x61, 0x76, 0x48, 0xb1, 0x26, 0xf7, 0xa0, 0x30,
	0x9b, 0x7f, 0x6a, 0xa0, 0x27, 0x23, 0xd7, 0xf7, 0x27, 0x0c, 0x9d, 0xc0, 0x86, 0xa3, 0xc8, 0x92,
	0xa5, 0x77, 0x50, 0x7e, 0x36, 0x85, 0xc7, 0x9c, 0x53, 0xc4, 0x57, 0xe3, 0xfa, 0x41, 0xcc, 0xad,
	0xc8, 0x7d, 0x47, 0xac, 0xd1, 0x8c, 0x93, 0x48, 0xd6, 0x2f, 0x9a, 0x86, 0xc4, 0x87, 0xee, 0x3b,
	0x72, 0x2e, 0x50, 0xb1, 0x8f, 0x59, 0xcc, 0x97, 0xa8, 0x05, 0x49, 0xad, 0x28, 0xc7, 0x82, 0x7b,
	0x06, 0x9b, 0xf3, 0x3f, 0x12, 0x2e, 0x36, 0xb4, 0x96, 0xde, 0xa9, 0xb5, 0xd5, 0x2f, 0xab, 0x3d,
	0xff, 0x65, 0xb5, 0x5f, 0x27, 0x04, 0x33, 0xa5, 0x36, 0x27, 0xe9, 0x5f, 0xcb, 0x24, 0xbf, 0xc6,
	0x24, 0xe2, 0xe2, 0x75, 0xb9, 0x1d, 0x4a, 0x95, 0xca, 0xa6, 0x30, 0xd1, 0x39, 0x54, 0x1c, 0xc5,
	0xb1, 0x98, 0xfa, 0xc2, 0x64, 0xbf, 0x7a, 0x6e, 0x99, 0xe4, 0x3f, 0x41, 0xd3, 0x70, 0x72, 0xe7,
	0xe6, 0x4f, 0x50, 0x49, 0xeb, 0x44, 0x01, 0xf3, 0x23, 0xb2, 0xa2, 0xd0, 0x0b, 0x28, 0xcf, 0x0b,
	0xb9, 0xfe, 0x84, 0x25, 0x55, 0xf6, 0x1e, 0x56, 0x11, 0xaa, 0x9b, 0xba, 0xb3, 0x38, 0x1c, 0xbf,
	0x85, 0x72, 0x76, 0xdb, 0xa3, 0x7d, 0xd8, 0xee, 0xdd, 0x58, 0x83, 0x37, 0xdf, 0xf6, 0xfa, 0xd7,
	0xd6, 0xed, 0xdb, 0xc1, 0x85, 0x75, 0x7d, 0x73, 0x7d, 0x51, 0x7d, 0x84, 0x76, 0x61, 0x6b, 0xc9,
	0xd1, 0xbb, 0xa9, 0x6a, 0xa8, 0x06, 0xbb, 0x0f, 0xe0, 0xcb, 0x57, 0xc3, 0xdb, 0xea, 0xda, 0xf1,
	0x1f, 0x1a, 0x18, 0xf9, 0x55, 0xa9, 0xd8, 0xab, 0xf3, 0xaf, 0x72, 0x09, 0xa0, 0xaa, 0xa1, 0xff,
	0x43, 0x6d, 0xa5, 0x4b, 0xd5, 0x41, 0x47, 0x70, 0xf0, 0x8f, 0xee, 0x0b, 0xb3, 0x5a, 0x40, 0x87,
	0x50, 0x5f, 0x49, 0x18, 0xbe, 0xe9, 0x77, 0xbf, 0xae, 0x16, 0x3b, 0x7d, 0x28, 0xbc, 0x1a, 0xf4,
	0xd1, 0xb9, 0x1c, 0x5d, 0xa1, 0x0c, 0x5a, 0x71, 0x41, 0xc9, 0x35, 0xd7, 0xeb, 0xab, 0x5c, 0xea,
	0x66, 0x9a, 0x8f, 0x46, 0xeb, 0xd2, 0x79, 0xfa, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xe8,
	0x27, 0x77, 0x12, 0x09, 0x00, 0x00,
}
